### ISSUE TITLE
Doesn't work with Nuxt 3

### ISSUE THREAD

**Issue by autorunman22** [jambonn/vue-concise-carousel#10]
Plugin:

```
import { Carousel, Slide } from '@jambonn/vue-concise-carousel';
import '@jambonn/vue-concise-carousel/lib/vue-concise-carousel.css'

export default defineNuxtPlugin(nuxtApp => {
    nuxtApp.vueApp.component(Carousel)
    nuxtApp.vueApp.component(Slide)
})
```

<img width="283" alt="image" src="https://github.com/jambonn/vue-concise-carousel/assets/4214419/7db9eeb5-40ae-4e40-afe8-e7a3146e73e2">

**Comment by jambonn** [comment]
I have tried and it still works with Nuxt 3. You can refer to my demo at [stackblitz](https://stackblitz.com/edit/github-jway3l?file=plugins%2Fcarousel.ts)

**Comment by autorunman22** [comment]
thanks. could be nuxt itself.

**Comment by ReiwuKleiwu** [comment]
This actually doesn't seem to work so well with Nuxt 3. I've tried your minimal example in a component inside of my Nuxt project and it indeed throws the warnings mentioned above.

<img width="480" alt="Bildschirmfoto 2023-07-23 um 15 18 16" src="https://github.com/jambonn/vue-concise-carousel/assets/23239135/524b1e2d-5f0d-4c25-9943-cffd500f3925">

**Comment by jambonn** [comment]
> This actually doesn't seem to work so well with Nuxt 3. I've tried your minimal example in a component inside of my Nuxt project and it indeed throws the warnings mentioned above.
> 
> <img alt="Bildschirmfoto 2023-07-23 um 15 18 16" width="480" src="https://user-images.githubusercontent.com/23239135/255395366-524b1e2d-5f0d-4c25-9943-cffd500f3925.png">

Can you upload the code or demo somewhere?

**Comment by ReiwuKleiwu** [comment]
It seems I can no longer reproduce the issue. Sorry for the confusion. 🙏🏻
