### ISSUE TITLE
great plugin

### ISSUE THREAD

**Issue by rrd108** [jambonn/vue-concise-carousel#12]
not an issue, I just did not find any other place where I cna contact you.

This plugin is cool :)

**Comment by jambonn** [comment]
There is no issue, why did you open one 😂? How can I assist you?

**Comment by rrd108** [comment]
I just wanted to express my appresiation :)

**Comment by jambonn** [comment]
> I just wanted to express my appresiation :)

I'm also glad that it has been helpful to you in your work 🎉
