### ISSUE TITLE
Navigation Elements don't update their state reactively

### ISSUE THREAD

**Issue by ReiwuKleiwu** [jambonn/vue-concise-carousel#22]
**Current Behavior:**
I am currently trying to write an Avatar-Picker using this carousel and each slide has 15 Avatars displayed, with over 500 avatars in total to choose from. Instead of fetching all avatars at once (and fully populating the carousel / slides), I always wanna fetch just the next slide (the next 15 avatars). And while the slide gets added to the DOM perfectly fine, the arrow button for the navigation stays disabled. 

**Expected Behvaior:**
The navigation buttons should change from disabled to enabled reactively, depending on whether there is a next slide or not (without having to go back and forth a slide yourself).

Minimal reproduction example: 
https://stackblitz.com/edit/github-jway3l-evhpsw?file=app.vue

In this example I create a carousel and add a new slide after 5 seconds. Make sure to go to the last slide (the third) before the new slide gets added after these 5 seconds.

**Comment by jambonn** [comment]
@ReiwuKleiwu I have just published a new version, please update to the latest version. This is your demo, and I have tested it: https://stackblitz.com/edit/github-jway3l-bn4fca?file=app.vue

**Comment by ReiwuKleiwu** [comment]
@jambonn Now everything works perfectly as expected! 

Thank you so much for keeping this plugin up to date, I appreciate your work.

**Comment by jambonn** [comment]
@ReiwuKleiwu Very glad to assist you, if you find the plugin helpful, please share it with others to help me. Thank you.
