### ISSUE TITLE
changing element style while changing slides

### ISSUE THREAD

**Issue by mukhrr** [jambonn/vue-concise-carousel#27]
I was wondering how can one achieve the following feature by vue-concise-carousel:

let's say, my image is placed to left side in slider and between transitions I want it smoothly change its styles from
```
  transform: translateX(0);
  transform: scale(0);
```
to 
```
  transform: translateX(10px);
  transform: scale(1.2);
```

**Comment by jambonn** [comment]
I don't understand why you need to use transform scale?

**Comment by mukhrr** [comment]
> I don't understand why you need to use transform scale?

I just want image to zoom out while changing. 
I mean something like the following:

https://github.com/jambonn/vue-concise-carousel/assets/71601329/8224bf53-51ce-4e04-9d93-9bbc5040647e

P.s: I implemented it by custom animation in my code source itself. However, it's worth adding such feature to this library.

**Comment by jambonn** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue?

**Comment by mukhrr** [comment]
I looked through and think this should be customized every time. I mean this is more related to element inside `Slide` component. Applying animation to Slide doesn't make sense.
