### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by ozgur-proreact** [jambonn/vue-concise-carousel#28]
The readme said "Vue 3 support is almost here with the vue-concise-carousel 2 rewrite. Check out the next". 

But I don't see any improvements. Is the library still maintaining?

**Comment by jambonn** [comment]
@ozgur-proreact Sorry for the late reply. Currently, the main branch is next, which supports Vue 3. If you want to support Vue 2, please checkout the master branch.
