### ISSUE TITLE
The slide boxes are not loaded in client end properly

### ISSUE THREAD

**Issue by Miltonbhowmick** [jambonn/vue-concise-carousel#29]
Hello, 
I used your slider. But somehow i was seeing that the slides were not loaded after page loaded. If i clicked on it, then the size of each slide increased.

![image](https://github.com/jambonn/vue-concise-carousel/assets/16919385/518e543d-0525-4e79-8adc-1ba3aa4ddf2a)

**Comment by jambonn** [comment]
Please report the issue in more detail, including a link to your GitHub project or on stackblitz.com..., as well as the steps to reproduce the issue. This will make it easier for me to support you.

**Comment by Miltonbhowmick** [comment]
> Please report the issue in more detail, including a link to your GitHub project or on stackblitz.com..., as well as the steps to reproduce the issue. This will make it easier for me to support you.

It was actually private project. Is there anyway to connect one to one communication?

**Comment by jambonn** [comment]
@Miltonbhowmick If it is a private project, please recreate the issue on Stackblitz.com for example.
