### ISSUE TITLE
Issue with auto-pagination when perpage prop is set to 1 and last slide is removed

### ISSUE THREAD

**Issue by BilalTariq01** [jambonn/vue-concise-carousel#30]
When utilizing the vue-concise-carousel component with the perpage prop set to 1, I encountered an issue regarding auto-pagination behavior. Specifically, if multiple slides are added and subsequently removed, the carousel fails to auto-paginate to the second-last slide after removing the last slide.

Steps to reproduce:

Set the perpage prop to 1.
Add multiple slides to the carousel.
Navigate to the last slide.
Remove the last slide.
Observe that the carousel does not auto-paginate to the second-last slide.
Expected behavior:
The carousel should automatically paginate to the second-last slide when the last slide is removed, regardless of the number of slides added or the perpage prop setting.

**Comment by jambonn** [comment]
@BilalTariq01 Can you create a demo issue on stackblitz.com? Or would you like to submit a pull request to address this issue?

**Comment by BilalTariq01** [comment]
Thank you for getting back to me. This issue has been resolved in the latest version (2.1.31). Previously, I encountered this problem in version 2.1.29.
