### ISSUE TITLE
Make Vue3 the default / Update readme

### ISSUE THREAD

**Issue by MickL** [jambonn/vue-concise-carousel#34]
Hey, thanks for this amazing library!

Vue3 is out for a long time and it seems like this library is working stable. Shouldnt the "next" branch be made the default in the readme and just use `npm install @jambonn/vue-concise-carousel`?

Also an example how to integrate into Nuxt could be added, I do it like this:

```ts
import { Carousel, Slide } from '@jambonn/vue-concise-carousel';
import '@jambonn/vue-concise-carousel/lib/vue-concise-carousel.css';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('Carousel', Carousel);
  nuxtApp.vueApp.component('Slide', Slide);
});
```

**Comment by jambonn** [comment]
Thank you for your contribution. I will promptly update the README file. I’m glad our library has been helpful to you.

**Comment by MickL** [comment]
Amazing! 
Yes it is great, but hard to find in the Vue/Nuxt ecosystem. Btw I open another issue for a feature request :)

**Comment by jambonn** [comment]
Do you have any tips for easier searching within the Vue/Nuxt ecosystem? Currently, I've added it to Vue Awesome.
