### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'adjustableHeight')

### ISSUE THREAD

**Issue by mohamed-rnd** [jambonn/vue-concise-carousel#37]
Hi

I always use this package and everthing is fine
But today when I tried to create a carousel I got this message
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'adjustableHeight')`

When I make the content of the slide only text it disappears, but when I add HTML (event an empty div) it appears

Something to be noted: There is another carousel in the page with HTML content and it's fine
Here is my Full HTML code for the broken carousel
```
<Carousel snap-align="center" :per-page="1" dir="ltr" :wrap-around="true" :transition="500"
    class="article-carousel">

    <Slide class="card">
        <div class="carousel-item">
            <div class="card">
            </div>
        </div>
    </Slide>

    <Slide class="card">
        <div class="carousel-item">
            <div class="card">
            </div>
        </div>
    </Slide>
    
    <Slide class="card">
        <div class="carousel-item">
            <div class="card">
            </div>
        </div>
    </Slide>

</Carousel>

```

**Comment by mohamed-rnd** [comment]
I figured out that this happened when the whole carousel was wrapped inside `<p>` by mistake

**Comment by jambonn** [comment]
@mohamed-rnd I’m very sorry for the delayed response on this matter. Basically, wrapping a carousel inside a <p> tag is incorrect HTML structure, so I believe this is not an issue with the package.
