### ISSUE TITLE
[Bug] Could not find a declaration file for module '@jambonn/vue-concise-carousel'.

### ISSUE THREAD

**Issue by moHaHa** [jambonn/vue-concise-carousel#8]
`main.ts`
```ts
import { createApp } from 'vue'
import { createRouter, createWebHistory } from 'vue-router'
import routes from 'virtual:generated-pages'
import { Carousel, Slide } from '@jambonn/vue-concise-carousel';
import App from './App.vue'
```

I got this error 
![image](https://user-images.githubusercontent.com/72744132/230496484-e8462a7b-4adb-4237-9b65-7a66f9db6706.png)

>Could not find a declaration file for module '@jambonn/vue-concise-carousel'. 
{path}/.pnpm/@jambonn+vue-concise-carousel@2.1.29_vue@3.2.47/node_modules/@jambonn/vue-concise-carousel/lib/vue-concise-carousel.cjs.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/jambonn__vue-concise-carousel` if it exists or add a new declaration (.d.ts) file containing `declare module '@jambonn/vue-concise-carousel';`ts(7016)
  
then , I run this commant to `npm i --save-dev @types/jambonn__vue-concise-carousel` 

I got 
> not found 
![image](https://user-images.githubusercontent.com/72744132/230496824-0a992bf0-de3a-4f68-a6ae-498ce64d07ab.png)

**Comment by moHaHa** [comment]
Related to #7

**Comment by jambonn** [comment]
This is not an issue. Currently, the package does not support TypeScript, but you can add `declare module '@jambonn/vue-concise-carousel';` to your .d.ts file.
